spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    enabled: false

postgres:
  repave: true
  db:
    name: splitr-db


