-- Phase 3: Data type migrations (MED-2, MED-3, MED-4)
-- TIMESTAMPTZ
ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE users ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
ALTER TABLE groups ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE groups ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
ALTER TABLE groups ALTER COLUMN invite_code_expires_at TYPE TIMESTAMPTZ;
ALTER TABLE groups ALTER COLUMN archived_at TYPE TIMESTAMPTZ;
ALTER TABLE expenses ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE expenses ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
ALTER TABLE settlements ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE settlements ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
ALTER TABLE group_members ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE group_members ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
ALTER TABLE group_members ALTER COLUMN joined_at TYPE TIMESTAMPTZ;
ALTER TABLE group_members ALTER COLUMN left_at TYPE TIMESTAMPTZ;
ALTER TABLE guest_users ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE guest_users ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
ALTER TABLE guest_users ALTER COLUMN token_expires_at TYPE TIMESTAMPTZ;
ALTER TABLE push_tokens ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE push_tokens ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
ALTER TABLE push_tokens ALTER COLUMN last_used_at TYPE TIMESTAMPTZ;
ALTER TABLE notification_log ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE notification_log ALTER COLUMN delivered_at TYPE TIMESTAMPTZ;
ALTER TABLE activity_log ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE exchange_rates ALTER COLUMN effective_date TYPE TIMESTAMPTZ;
ALTER TABLE exchange_rates ALTER COLUMN fetched_at TYPE TIMESTAMPTZ;
ALTER TABLE categories ALTER COLUMN created_at TYPE TIMESTAMPTZ;
